import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — LilyAI',
  description: 'How LilyAI collects, uses, and protects your personal data.',
}

export default function PrivacyPolicyPage() {
  return (
    <>
      <p className="legal-note">
        DRAFT — pending review by a qualified solicitor before paid launch. Not yet legally vetted.
      </p>
      <article className="page-sheet">
        <div className="pp-kicker">LilyAI</div>
        <h1>Privacy Policy</h1>
        <p className="pp-updated">Last updated: 30 June 2026</p>
        <div className="pp-rule" />

        <p>
          This Privacy Policy explains how LilyAI (&ldquo;we&rdquo;, &ldquo;us&rdquo;) collects, uses,
          and safeguards your personal data when you use our document intelligence service (the
          &ldquo;Service&rdquo;). We are committed to protecting your privacy and handling your data in
          an open and transparent manner.
        </p>

        <h2>1. Who we are</h2>
        <p>
          LilyAI is the data controller responsible for your personal data. We are registered with the
          UK Information Commissioner&rsquo;s Office (ICO).
        </p>
        <p>
          <strong>ICO Registration Number: [ICO-NUMBER-PENDING]</strong>
        </p>

        <h2>2. Data we collect</h2>
        <ul>
          <li>Account information (name and email address) provided via Auth0 at sign-up.</li>
          <li>Documents you upload and the text extracted from them for retrieval and answering.</li>
          <li>Questions you ask and the answers generated by the Service.</li>
          <li>Usage data such as query counts and storage consumed, used to enforce plan limits.</li>
        </ul>

        <h2>3. How we use your data</h2>
        <ul>
          <li>To provide the Service: indexing your documents and answering your questions.</li>
          <li>To authenticate you and secure your account.</li>
          <li>To enforce subscription limits and bill you where applicable.</li>
          <li>To maintain, monitor, and improve the reliability of the Service.</li>
        </ul>

        <h2>4. Legal basis for processing</h2>
        <p>
          We process your personal data to perform our contract with you, to comply with legal
          obligations, and where it is in our legitimate interests to operate and improve the Service,
          provided those interests are not overridden by your rights.
        </p>

        <h2>5. Sharing and sub-processors</h2>
        <p>
          We use trusted third-party providers to deliver the Service, including authentication,
          cloud hosting, storage, and AI model providers. These providers process data on our behalf
          under appropriate data-processing agreements. We do not sell your personal data.
        </p>

        <h2>6. Data retention</h2>
        <p>
          We retain your account data and documents for as long as your account is active. You may
          delete documents at any time, and you may request deletion of your account and associated
          data by contacting us.
        </p>

        <h2>7. Your rights</h2>
        <p>
          Under UK data protection law you have the right to access, correct, delete, restrict, or
          object to the processing of your personal data, and the right to data portability. To
          exercise any of these rights, please contact us. You also have the right to lodge a
          complaint with the ICO at ico.org.uk.
        </p>

        <h2>8. Contact</h2>
        <p>
          For any privacy questions or to exercise your rights, contact us at privacy@lilyai.dev.
        </p>
      </article>
    </>
  )
}
